TigerAppsOrg/tiger-junction

package-lock.json
package.json
src/routes/(landing)/+page.svelte

New landing

---

package-lock.json
package.json
src/lib/components/elements/TogTog.svelte
src/lib/components/recal/Top.svelte
src/lib/components/recal/elements/adv/AdvancedSearch.svelte
src/lib/components/recal/elements/save/AddSchedule.svelte
src/lib/components/recal/elements/save/EditSchedule.svelte
src/lib/components/recal/elements/search/SearchBar.svelte
src/lib/stores/recal.ts

Implement filter and sort by rating; bug fixes.

More recal filters

---

src/lib/components/elements/StdModal.svelte
src/lib/components/recal/modals/EditCb.svelte
src/lib/components/recal/modals/ExportCal.svelte
src/lib/components/recal/modals/ManageCb.svelte
src/lib/components/recal/modals/RecalColors.svelte
src/lib/components/recal/modals/RecalPalettes.svelte
src/lib/components/recal/modals/RecalStats.svelte
src/lib/components/recal/modals/RecalUtils.svelte
src/lib/components/recal/modals/ShareCal.svelte
src/lib/components/recal/modals/SiteTimer.svelte
src/lib/components/recal/modals/TimeSelect.svelte
src/lib/scripts/ReCal+/cardFunctions.ts
tailwind.config.js

Fix a breaking bug caused by spamming the add button on MinimalBase cards, causing a crash due to section data not loading in time. Refactor the standard modal format into its own Svelte component. Place Recal modals into one folder.

Major bug fix

---

README.md
package-lock.json
package.json
src/lib/components/recal/Calendar.svelte

Fix the clashing algorithm used to render CalBoxes on the calendar. The new algorithm isn't completely perfect, but it is much better than the old algorithm and makes courses with high amounts of clashing (ex. CHM 301) actually useable.

Fix clashing

---

README.md
package-lock.json
package.json
src/lib/components/recal/Calendar.svelte
src/lib/components/recal/Top.svelte
src/lib/components/recal/elements/save/AddSchedule.svelte
src/lib/components/recal/elements/save/CalBox.svelte
src/lib/components/recal/elements/save/EditSchedule.svelte
src/lib/components/recal/modals/AdvancedSearch.svelte
src/lib/constants.ts
src/lib/scripts/convert.ts
src/lib/stores/recal.ts
src/routes/(apps)/+layout.ts
src/routes/(apps)/recalplus/+page.svelte
src/routes/+layout.svelte

Many minor improvements. Most important one is having the rightmost CalBox expand to the right to fill in all available whitespace. I chose this design decision over the one that ReCal uses for efficiency since TigerJunction allows custom blocks. Fix the formatting for schedules when they overflow, which also makes the app more compatible. Switch to client side rendering to save Vercel edge function execution time. Place checks on the length of the schedule title (checks existed in the backend already, but this improves the UX by giving explicit errors instead of throwing a generic "try again" error). Create "reset to default" button for advanced search, and implement a 10 schedule per term cap per user to prevent database bloat. Readme update and bug fixes.

Misc prod updates

---

package-lock.json
package.json
src/lib/components/recal/Top.svelte
src/lib/components/recal/modals/AdvancedSearch.svelte
src/lib/scripts/ReCal+/getLinks.ts
src/lib/stores/recal.ts

Fix TigerSnatch links, remove the confusing search by title/code options, and temporarily remove the tooltips option until they are fully implemented.

Prod updates 2

---

package-lock.json
package.json
src/lib/components/recal/elements/cards/MinimalBase.svelte
src/lib/components/recal/modals/RecalUtils.svelte
tailwind.config.js

Remove the TigerSnatch button in non-current semester. Remove DaisyUI.

Fix tigersnatch

---

.gitignore
package-lock.json
package.json
src/lib/scripts/ReCal+/fetchDb.ts
src/lib/stores/recal.ts
src/routes/(apps)/recalplus/+page.server.ts
src/routes/(apps)/recalplus/+page.svelte
src/routes/(apps)/recalplus/+page.ts

Fetch course data for current term on page load to decrease net load time.

Prefetch redis

---

package-lock.json
package.json
src/lib/components/recal/Calendar.svelte
src/lib/stores/recal.ts

Add optional time markers (toggleable in advanced search settings) for the calendar.

Time markers

---

db/icalStorage.sql
package-lock.json
package.json
src/lib/components/general/ModalLib.svelte
src/lib/components/recal/Calendar.svelte
src/lib/components/recal/modals/ExportCal.svelte
src/lib/components/recal/modals/RecalUtils.svelte
src/lib/constants.ts
src/lib/scripts/ReCal+/ical.ts
src/lib/scripts/convert.ts
src/routes/api/client/calendar/[uuid]/+server.ts

Implement the calendar export feature.

Calendar export

---

package-lock.json
package.json
src/app.pcss
src/lib/components/elements/Checkpill.svelte
src/lib/components/elements/StdButton.svelte
src/lib/components/elements/StdModal.svelte
src/lib/components/elements/TogTog.svelte
src/lib/components/recal/Top.svelte
src/lib/components/recal/elements/save/AddSchedule.svelte
src/lib/components/recal/elements/save/EditSchedule.svelte
src/lib/components/recal/modals/AdvancedSearch.svelte
src/lib/components/recal/modals/ExportCal.svelte
src/lib/components/recal/modals/RecalColors.svelte
src/routes/(landing)/+page.svelte
src/routes/+error.svelte

Minor UI/UX updates to standardize style throughout and make it easier to keep a consistent style as more features are added.

Minor updates

---

package-lock.json
package.json
src/lib/components/elements/Checkpill.svelte
src/lib/components/elements/TogTog.svelte
src/lib/components/recal/Top.svelte
src/lib/components/recal/modals/AdvancedSearch.svelte

Few improvements to advanced search UI/UX, including fixing the style to match theme, making checkpills tababble, and adding buttons to check all/none subfilters at once (ex. set all dists to true or false).

Adv search theme

---

src/lib/components/recal/elements/search/SearchBar.svelte

Check for the ready store to be true before opening advanced search settings

Ensure data is loaded for adv search

---

db/createTables.sql
package-lock.json
package.json
src/lib/components/recal/modals/AdvancedSearch.svelte
src/lib/scripts/ReCal+/conflict.ts
src/lib/stores/recal.ts
src/lib/stores/rsections.ts
src/lib/types/regTypes.ts
src/routes/admin/+page.svelte
supabase/functions/courses/index.ts

Add search by available/non-conflicting, and fix some bugs related to it.

Smart search

---

src/lib/stores/rsections.ts
src/routes/(apps)/recalplus/+page.server.ts
src/routes/(apps)/recalplus/+page.svelte

Preload section data from current term in order to save on supabase egress

Preload section data from term

---

src/lib/components/recal/elements/save/CalBox.svelte
src/lib/components/recal/elements/save/Saved.svelte
src/lib/stores/recal.ts
src/lib/stores/rpool.ts
tailwind.config.js

Make the enrollment and room details smaller on the CalBoxes to stop overflowing. Add text next to the export button to make it obvious. Fix a bug where the added courses were not being removed from the search course data (for some reason). Change name from "Show Enrollments" to "Always Show Enrollments" to better reflect what the button does.

Final touches

---

db/icalStorage.sql
src/lib/changeme.ts
src/lib/components/recal/modals/ExportCal.svelte
src/lib/scripts/ReCal+/ical.ts
src/lib/scripts/scraper/getallcourses.ts
src/routes/admin/+page.svelte
src/routes/api/server/refresh/ical/+server.ts
vercel.json

Create a cron job (that runs on Vercel serverless functions every 24 hours) to automatically update calendar exports. Slightly modify the wording and style of the export modal to be more clear and precise.

Export improvement

---

README.md
src/routes/(landing)/(info)/contact/+page.svelte
src/routes/(landing)/(info)/privacy/+page.svelte
src/routes/(landing)/(info)/tos/+page.svelte

Change email from motoaki@princeton.edu to it.admin@tigerapps.org as part of the individual -> organization transfer.

Change email

---

src/lib/stores/events.ts
src/routes/(apps)/recalplus/+page.svelte
src/routes/(apps)/reqtree/+page.server.ts
src/routes/(apps)/reqtree/+page.svelte

Boilerplate reqtree

---

apps/prerequisites/scripts/yaml_interpreter.py

Compiler for course prerequisite data.

Prerequisite YAML Compiler
